name: haplongliner
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - biopython
  - pyfaidx
  - edlib
  - tqdm
  - minimap2
  - emboss
  - blast
  - repeatmasker
  - pip
  - pip:
      - -e .
