import argparse
import sys
from textwrap import dedent

from .module1_RM import run_module1
from .module2_SV import run_module2
from .module3_DB import run_module3
from .utils import check_dependencies

__version__ = "0.1.0"

HS1_URL = "https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.fa.gz"
HG38_URL = "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz"

def main():
    # Top-level parser mimicking the seqtk style help output
    description = dedent(
        f"""haplongliner

        Usage:   haplongliner <command> <arguments>
        Version: {__version__}

        Command: rm        RepeatMasker-based L1 discovery
                 sv        SV-based L1 discovery
                 db        L1 sequence repository
        """
    )

    parser = argparse.ArgumentParser(
        prog="haplongliner",
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=description,
        add_help=False,
    )

    parser.add_argument(
        "-h",
        "--help",
        action="help",
        default=argparse.SUPPRESS,
        help="Show this help message and exit.",
    )
    parser.add_argument(
        "-v",
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
        help="Show program's version number and exit.",
    )

    subparsers = parser.add_subparsers(dest="command")

    # Module 1: RepeatMasker-based
    parser_rm = subparsers.add_parser(
        "rm",
        add_help=False,
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Usage:   haplongliner rm [options]",
        help="Module 1: RepeatMasker-based L1 discovery",
    )
    parser_rm._positionals.title = ""
    parser_rm._optionals.title = "Options"
    parser_rm.add_argument("-i", "--in", dest="input", required=True, help="Input haploid assembly FASTA")
    parser_rm.add_argument("-m", "--mask", required=True, help="RepeatMasker BED or .out file")

    parser_rm.add_argument(
        "--log-skipped",
        dest="log_skipped",
        help="File to log malformed RepeatMasker lines",
    )

    ref_group = parser_rm.add_mutually_exclusive_group(required=True)
    ref_group.add_argument("-r", "--reference", choices=["hs1", "hg38"], help="Reference genome: 'hs1' or 'hg38' (remote)")
    ref_group.add_argument("-c", "--custom", help="Custom reference FASTA or gzipped FASTA (local path)")

    parser_rm.add_argument("-o", "--out", dest="output", required=True, help="Output directory for intermediate files")
    parser_rm.add_argument("-h", "--help", action="help", default=argparse.SUPPRESS,
                           help="Show this help message and exit.")

    # Module 2: SV-based
    parser_sv = subparsers.add_parser(
        "sv",
        add_help=False,
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Usage:   haplongliner sv [options]",
        help="Module 2: SV-based L1 discovery",
    )
    parser_sv._positionals.title = ""
    parser_sv._optionals.title = "Options"
    parser_sv.add_argument("-i", "--in", dest="input", required=True, help="Input haploid assembly FASTA")
    parser_sv.add_argument("-s", "--sv", required=True, help="Structural variant callset")
    parser_sv.add_argument("-l", "--l1ref", required=True, help="Pangenome-level L1 reference FASTA")
    parser_sv.add_argument("-o", "--out", dest="output", required=True, help="Output BED file")
    parser_sv.add_argument("-h", "--help", action="help", default=argparse.SUPPRESS,
                           help="Show this help message and exit.")

    # Module 3: Database
    parser_db = subparsers.add_parser(
        "db",
        add_help=False,
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Usage:   haplongliner db [options]",
        help="Module 3: L1 sequence repository",
    )
    parser_db._positionals.title = ""
    parser_db._optionals.title = "Options"
    parser_db.add_argument("-o", "--out", dest="output", required=True, help="Output directory or file")
    parser_db.add_argument("-h", "--help", action="help", default=argparse.SUPPRESS,
                           help="Show this help message and exit.")

    # Hide the autogenerated positional arguments section in the main help
    parser._action_groups = [g for g in parser._action_groups if g.title != "positional arguments"]

    args = parser.parse_args()

    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    if args.command:
        check_dependencies()

    if args.command == "rm":
        # Determine reference path/URL
        if args.reference == "hs1":
            reference = HS1_URL
        elif args.reference == "hg38":
            reference = HG38_URL
        else:
            reference = args.custom
        run_module1(
            args.input,
            args.mask,
            reference,
            args.output,
            log_skipped=args.log_skipped,
        )
    elif args.command == "sv":
        run_module2(args.input, args.sv, args.l1ref, args.output)
    elif args.command == "db":
        run_module3(args.output)

if __name__ == "__main__":
    main()