import os
import re
import sys
import gzip
import itertools
import tempfile
from pathlib import Path
from typing import Dict, List, Tuple, Iterable, Set

from .utils import (
    run_quiet,
    verify_fasta_file,
    verify_sv_file,
    verify_repeatmasker_file,
    verify_blast_db,
    read_paf,
    _fix_blast_query_names,
)
from pyfaidx import Fasta


def _revcomp(seq: str) -> str:
    complement = str.maketrans("ACGTacgtNn", "TGCAtgcaNn")
    return seq.translate(complement)[::-1]


def _parse_target_info(info: str) -> Tuple[str, int, int, str]:
    """Return ``(scaf, start, end, strand)`` from target info string."""
    parts = info.split(",")
    if len(parts) < 4:
        raise ValueError(f"Malformed info field: {info}")
    scaf = parts[0]
    start = int(parts[1])
    end = int(parts[2])
    if len(parts) >= 5:
        strand = parts[4]
    else:
        strand = parts[3]
    return scaf, start, end, strand


from .module1_RM import download_if_needed, _fix_getorf_headers, parse_repeatmasker
from .extract_l1 import _expand_te_names


from .find_longest_orf import find_longest_orf
from .find_intact_orf import find_intact_orf


# use shared PAF parser from utils for backward compatibility
_read_paf = read_paf


def _load_master_coords(paths: Iterable[Path]) -> Dict[str, Tuple[str, int, int, str]]:
    """Return mapping ``name -> (chrom, start, end, strand)`` from master BED files."""
    coords: Dict[str, Tuple[str, int, int, str]] = {}
    for path in paths:
        with open(path) as fh:
            for line in fh:
                if not line.strip() or line.startswith("#"):
                    continue
                fields = line.strip().split()
                if len(fields) < 5:
                    continue
                if len(fields) >= 6:
                    chrom, start, end, name, *_rest, strand = fields[:6]
                else:
                    chrom, start, end, name, strand = fields[:5]
                try:
                    coords[name] = (chrom, int(start), int(end), strand)
                except ValueError:
                    continue
    return coords


def _convert_rm_out_to_bed(out_path: Path) -> Path:
    """Convert RepeatMasker .out[.gz] file to temporary BED6 entries."""

    tmp = tempfile.NamedTemporaryFile("w", suffix=".bed", delete=False)
    opener = gzip.open if str(out_path).endswith(".gz") else open

    with opener(out_path, "rt") as fin, tmp:
        first_lines = [fin.readline() for _ in range(4)]
        if any("SW" in l and "perc" in l for l in first_lines):
            iterator = fin
        else:
            iterator = itertools.chain(first_lines, fin)

        for line in iterator:
            if not line.strip() or line.startswith(("#", "track", "browser")):
                continue
            fields = re.split(r"\s+", line.strip())
            if len(fields) < 14 or not fields[5].isdigit() or not fields[6].isdigit():
                continue
            chrom = fields[4]
            start = int(fields[5]) - 1
            end = int(fields[6])
            strand = "-" if fields[8] == "C" else "+"
            name = fields[9]
            length = end - start
            tmp.write(f"{chrom}\t{start}\t{end}\t{name}\t{length}\t{strand}\n")

    return Path(tmp.name)


def _liftover_l1s(
    aln_paf: Path,
    ref_bed: Path,
    min_length: int,
    master_files: Iterable[Path] | None = None,
    *,
    mapq: int = 0,
    min_align_len: int = 0,
    max_div: float = 2.0,
) -> List[Tuple[str, int, int, str, int, str, str, str, int, int]]:
    """Infer reference coordinates for each L1 using whole-genome alignments.

    ``aln_paf`` should be generated by mapping the target assembly to the
    reference assembly with minimap2 using the ``-c --cs`` options. ``ref_bed``
    must contain the L1 coordinates on the reference assembly. The returned list
    contains tuples of ``(chrom, start, end, name, length, strand, plus_info,
    minus_info, t_start, t_end)`` where ``plus_info`` and ``minus_info`` are
    ``scaffold,start,end,strand`` strings describing the lifted coordinates on
    the target assembly.

    ``mapq``, ``min_align_len`` and ``max_div`` are forwarded to ``liftover_paf``
    and default to ``-q 0 -l 0 -d 2.0``.
    """

    if master_files is None:
        master_files = [ref_bed]

    ref_coords = _load_master_coords(master_files)

    # run liftover_paf.py and capture the output
    import importlib.util
    import io
    import contextlib

    script_path = Path(__file__).resolve().parents[1] / "scripts" / "liftover_paf.py"
    spec = importlib.util.spec_from_file_location("liftover_paf", script_path)
    liftover_paf = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(liftover_paf)

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        # use permissive parameters so short alignments are retained
        # (-q 0 -l 0 -d 2.0 by default)
        liftover_paf.liftover_paf(
            str(aln_paf),
            str(ref_bed),
            mapq,
            min_align_len,
            max_div,
            False,
        )

    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]] = []
    for line in buf.getvalue().splitlines():
        if not line.strip():
            continue
        fields = line.split("\t")
        if len(fields) < 6:
            continue
        t_chrom, t_start_s, t_end_s, name_field, _score, t_strand = fields[:6]
        try:
            t_start = int(t_start_s)
            t_end = int(t_end_s)
        except ValueError:
            continue
        try:
            _qchrom, q_start, q_end, _qstrand, q_name = name_field.split(",", 4)
        except ValueError:
            continue

        if q_name not in ref_coords:
            continue
        rchrom, rstart, rend, rstrand = ref_coords[q_name]
        length = rend - rstart
        if length < min_length:
            continue

        plus_info = f"{t_chrom},{t_start},{t_end},{t_strand}"
        minus_info = plus_info
        lifted.append(
            (
                rchrom,
                rstart,
                rend,
                q_name,
                length,
                rstrand,
                plus_info,
                minus_info,
                t_start,
                t_end,
            )
        )

    return lifted


def _write_bed(
    entries: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    path: Path,
) -> None:
    with open(path, "w") as out:
        for (
            chrom,
            start,
            end,
            name,
            length,
            strand,
            plus_info,
            minus_info,
            *_,
        ) in entries:
            out.write(
                f"{chrom}\t{start}\t{end}\t{name}\t{length}\t{strand}\t{plus_info}\t{minus_info}\n"
            )


def _read_lifted_bed(path: Path) -> Dict[str, List[Tuple[str, int, int, str, Set[str]]]]:
    """Return mapping ``name -> list of lifted coordinates`` from liftover_paf output."""

    lifted: Dict[str, List[Tuple[str, int, int, str, Set[str]]]] = {}
    with open(path) as fh:
        for line in fh:
            if not line.strip() or line.startswith("#"):
                continue
            fields = line.rstrip().split("\t")
            if len(fields) < 6:
                continue
            scaf, s_s, e_s, info, *_rest, strand = fields[:6]
            try:
                start = int(s_s)
                end = int(e_s)
            except ValueError:
                continue
            parts = info.split(",")
            if len(parts) < 5:
                continue
            _qchrom, _qs, _qe, _qstrand, name, *tags = parts
            lifted.setdefault(name, []).append((scaf, start, end, strand, set(tags)))
    return lifted


def _filter_reference_bed(
    raw_ref: Path, min_length: int, te: str, teref: str
) -> Path:
    """Filter reference BED records by TE family and length.

    When ``teref`` is ``"hprc"`` the BED lacks TE family names in column 4.
    In that case assume all entries are L1 elements and only apply the
    length filter.
    """

    tmp = tempfile.NamedTemporaryFile("w", suffix=".bed", delete=False)
    if teref == "hprc":
        with open(raw_ref) as inp, open(tmp.name, "w") as out:
            for line in inp:
                if not line.strip() or line.startswith("#"):
                    continue
                fields = line.rstrip().split("\t")
                if len(fields) < 3:
                    continue
                try:
                    start = int(fields[1])
                    end = int(fields[2])
                except ValueError:
                    continue
                if (end - start) >= min_length:
                    out.write(line if line.endswith("\n") else line + "\n")
    else:
        run_quiet(
            [
                sys.executable,
                "-m",
                "haplongliner.extract_l1",
                str(raw_ref),
                "-o",
                tmp.name,
                "-l",
                str(min_length),
                "-t",
                te,
            ],
            check=True,
        )
    tmp.close()
    return Path(tmp.name)


def _create_lifted_reorg(
    lifted_bed: Path, ref_bed: Path, out_path: Path
) -> List[Tuple[str, int, int, str, int, str, str, str, int, int]]:
    """Write ``lifted_reorg.bed`` and return lifted entries for downstream steps."""

    mapping = _read_lifted_bed(lifted_bed)
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]] = []

    with open(ref_bed) as inp, open(out_path, "w") as out:
        for line in inp:
            if not line.strip() or line.startswith("#"):
                continue
            f = line.rstrip().split("\t")
            if len(f) < 6:
                continue
            chrom, start_s, end_s, name, length_s, strand = f[:6]
            try:
                start = int(start_s)
                end = int(end_s)
                length = int(length_s)
            except ValueError:
                continue

            infos = mapping.get(name)
            if not infos:
                out.write(
                    f"{chrom}\t{start}\t{end}\t{name}\t{length}\t{strand}\tna\n"
                )
                continue

            info_strs: List[str] = []
            for scaf, s, e, t_strand, tags in infos:
                tag_str = ""
                if "t5" in tags:
                    tag_str += ",t5"
                if "t3" in tags:
                    tag_str += ",t3"
                info = f"{scaf},{s},{e},{e - s},{t_strand}{tag_str}"
                info_strs.append(info)
                lifted.append(
                    (
                        chrom,
                        start,
                        end,
                        name,
                        length,
                        strand,
                        info,
                        info,
                        s,
                        e,
                    )
                )

            info_joined = ";".join(info_strs)
            out.write(
                f"{chrom}\t{start}\t{end}\t{name}\t{length}\t{strand}\t{info_joined}\n"
            )

    return lifted

def _parse_sv(
    sv_path: Path, log_path: Path | None = None
) -> Tuple[List[Tuple[str, int, int]], List[Tuple[str, int, int, str]]]:
    """Parse a simple VCF or BED SV file and return deletion and insertion regions.

    For insertions the inserted sequence is also returned if present. Unrecognized
    lines are written to ``log_path`` if provided."""
    deletions: List[Tuple[str, int, int]] = []
    insertions: List[Tuple[str, int, int, str]] = []
    is_vcf = sv_path.suffix.lower().endswith("vcf") or sv_path.suffix.lower() == ".gz"
    import gzip

    skipped: List[str] = []
    opener = gzip.open if str(sv_path).endswith(".gz") else open
    with opener(sv_path, "rt") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.rstrip().split("\t")
            if is_vcf or len(fields) > 5:
                try:
                    chrom = fields[0]
                    pos = int(fields[1]) - 1
                    info = fields[7] if len(fields) > 7 else ""
                    svtype = None
                    end = None
                    for item in info.split(";"):
                        if item.startswith("SVTYPE="):
                            svtype = item.split("=", 1)[1]
                        elif item.startswith("END="):
                            end = int(item.split("=", 1)[1]) - 1
                    if svtype == "DEL" and end is not None:
                        deletions.append((chrom, pos, end))
                    elif svtype == "INS":
                        alt = fields[4]
                        seq = "" if alt.startswith("<") else alt
                        insertions.append((chrom, pos, pos + 1, seq))
                except Exception:
                    skipped.append(line.rstrip())
            else:
                try:
                    chrom, start, end = fields[:3]
                    svtype = fields[3].upper() if len(fields) > 3 else ""
                    if svtype == "DEL":
                        deletions.append((chrom, int(start), int(end)))
                    elif svtype == "INS":
                        seq = fields[4] if len(fields) > 4 else ""
                        insertions.append((chrom, int(start), int(end), seq))
                except Exception:
                    skipped.append(line.rstrip())
    if log_path and skipped:
        with open(log_path, "w") as logf:
            logf.write("\n".join(skipped) + "\n")
    return deletions, insertions


def _bedtools_intersect(a: Path, b: Path, output: Path) -> None:
    with open(output, "w") as out:
        run_quiet(
            ["bedtools", "intersect", "-wa", "-wb", "-a", str(a), "-b", str(b)],
            check=True,
            stdout=out,
        )


def _collect_long_insertions(
    insertions: List[Tuple[str, int, int, str]],
    inter_ins: Path,
    min_length: int,
) -> List[Tuple[str, int, int, str, str]]:
    """Return insertion entries not overlapping lifted TEs with length >= ``min_length``.

    The returned list contains tuples of ``(chrom, start, end, seq, name)`` where
    ``name`` is generated from the coordinates (``INS_<chrom>_<start>``).
    """

    overlapped: Set[Tuple[str, int, int]] = set()
    if inter_ins.exists():
        with open(inter_ins) as fh:
            for line in fh:
                f = line.strip().split("\t")
                if len(f) >= 11:
                    try:
                        chrom = f[7]
                        start = int(f[8])
                        end = int(f[9])
                    except ValueError:
                        continue
                    overlapped.add((chrom, start, end))

    extras: List[Tuple[str, int, int, str, str]] = []
    for chrom, start, end, seq in insertions:
        if len(seq) >= min_length and (chrom, start, end) not in overlapped:
            name = f"INS_{chrom}_{start}"
            extras.append((chrom, start, end, seq, name))

    return extras


def _classify_sv(
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    deletions: List[Tuple[str, int, int]],
    insertions: List[Tuple[str, int, int, str]],
    outdir: Path,
    lifted_bed: Path,
) -> Tuple[Dict[str, str], Dict[str, str]]:
    """Write SV BED files and intersect with lifted coordinates.

    Returns a status dictionary and a mapping of insertion sequences by TE name."""

    del_bed = outdir / "sv_del.bed"
    ins_bed = outdir / "sv_ins.bed"

    with open(del_bed, "w") as out:
        for chrom, start, end in deletions:
            out.write(f"{chrom}\t{start}\t{end}\n")

    with open(ins_bed, "w") as out:
        for chrom, start, end, seq in insertions:
            out.write(f"{chrom}\t{start}\t{end}\t{seq}\n")

    inter_del = outdir / "intersect_del.bed"
    inter_ins = outdir / "intersect_ins.bed"
    _bedtools_intersect(lifted_bed, del_bed, inter_del)
    _bedtools_intersect(lifted_bed, ins_bed, inter_ins)

    status: Dict[str, str] = {
        name: "present" for _, _, _, name, _, _, _, _, _, _ in lifted
    }
    ins_seqs: Dict[str, str] = {}
    with open(inter_del) as fh:
        for line in fh:
            f = line.strip().split("\t")
            # expect 7 columns from lifted_reorg.bed and 3 from the deletion BED entry
            if len(f) < 10:
                continue
            a_start = int(f[1])
            a_end = int(f[2])
            name = f[3]
            # deletion BED columns appear after the lifted fields in the
            # intersection result as: ``chrom`` ``start`` ``end``.  Skip the
            # chromosome column and parse the start/end coordinates.
            d_start = int(f[8])
            d_end = int(f[9])
            overlap = max(0, min(a_end, d_end) - max(a_start, d_start))
            del_len = d_end - d_start
            cov = overlap / del_len if del_len else 0
            if cov >= 0.95:
                status[name] = "missing"
            else:
                status[name] = "absent"

    with open(inter_ins) as fh:
        for line in fh:
            f = line.strip().split("\t")
            # expect 7 columns from lifted_reorg.bed and 4 from the insertion BED entry
            if len(f) >= 11:
                name = f[3]
                seq = f[10]
                ins_seqs[name] = seq

    return status, ins_seqs


def _extract_sequences(
    fasta: Path,
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    status: Dict[str, str],
    ins_seqs: Dict[str, str],
    out_fa: Path,
    min_length: int,
    extra_ins: List[Tuple[str, int, int, str, str]] | None = None,
) -> None:
    """Extract candidate TE sequences from the target assembly."""

    fa = Fasta(str(fasta))

    with open(out_fa, "w") as out:
        for _, _, _, name, _, _, plus_info, _, t_start, t_end in lifted:
            scaf, _ps, _pe, t_strand = _parse_target_info(plus_info)
            seq = fa[scaf][t_start:t_end].seq
            if t_strand == "-":
                seq = _revcomp(seq)
            if seq:
                header = f"{name},{scaf},{t_start},{t_end},{t_strand}"
                out.write(f">{header}\n{seq}\n")

        for name, seq in ins_seqs.items():
            if len(seq) >= min_length:
                out.write(f">{name}_ins\n{seq}\n")

        if extra_ins:
            for chrom, start, end, seq, name in extra_ins:
                if len(seq) >= min_length:
                    header = f"{name},{chrom},{start},{end},."
                    out.write(f">{header}\n{seq}\n")


def _write_sv_sequences(
    fasta: Path,
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    status: Dict[str, str],
    ins_seqs: Dict[str, str],
    out_fa: Path,
    extra_ins: List[Tuple[str, int, int, str, str]] | None = None,
    present: Set[str] | None = None,
    intact: Set[str] | None = None,
) -> None:
    """Write sequences from the target assembly for ALN and INS entries."""

    fa = Fasta(str(fasta))
    if present is None:
        present = set()
    if intact is None:
        intact = set()
    extras = extra_ins or []

    with open(out_fa, "w") as out:
        for (
            _chrom,
            _start,
            _end,
            name,
            _length,
            _strand,
            plus_info,
            _minus_info,
            t_start,
            t_end,
        ) in lifted:
            base_stat = status.get(name, "present")
            scaf, *_rest, t_strand = _parse_target_info(plus_info)

            if name in ins_seqs:
                sv_stat = "INS"
            elif base_stat in {"missing", "absent"}:
                sv_stat = "DEL"
            else:
                sv_stat = "ALN"

            target_info = (
                f"{scaf},{t_start},{t_end},{t_end - t_start},{t_strand},{sv_stat}"
            )

            if sv_stat == "ALN":
                seq = fa[scaf][t_start:t_end].seq
                if t_strand == "-":
                    seq = _revcomp(seq)
                out.write(f">{target_info}\n{seq}\n")
            elif sv_stat == "INS":
                seq = ins_seqs.get(name, "")
                if seq:
                    out.write(f">{target_info}\n{seq}\n")

        for chrom, start, end, seq, name in extras:
            key = f"{name},{chrom},{start}"
            if key not in present and key not in intact:
                continue
            target_info = f"{chrom},{start},{end},{end - start},.,INS"
            out.write(f">{target_info}\n{seq}\n")


def _parse_repeatmasker(out_file: Path, l1_len: int, cov_thresh: float) -> Set[str]:
    """Return names of sequences covering ``cov_thresh`` of the L1 reference."""
    coverage: Dict[str, int] = {}
    with open(out_file) as fh:
        for line in fh:
            if line.startswith(" "):
                parts = line.split()
                if len(parts) >= 14 and re.search(r"L1", parts[9]):
                    name = parts[4]
                    rep_start = int(parts[11].strip("()"))
                    rep_end = int(parts[12].strip("()"))
                    cov = abs(rep_end - rep_start) + 1
                    coverage[name] = coverage.get(name, 0) + cov
    return {n for n, c in coverage.items() if c / l1_len >= cov_thresh}


def _validate_orfs(candidate_fa: Path) -> Tuple[Set[str], Set[str]]:
    """Return sets of names with >90% ORF coverage and with intact ORFs."""
    present: Set[str] = set()
    intact: Set[str] = set()
    if candidate_fa.stat().st_size == 0:
        return present, intact

    orf_fa = candidate_fa.with_name(candidate_fa.stem + "_.orf.fa")
    run_quiet(
        [
            "getorf",
            "-sequence",
            str(candidate_fa),
            "-find",
            "1",
            "-outseq",
            str(orf_fa),
        ],
        check=True,
    )
    _fix_getorf_headers(orf_fa, candidate_fa)

    blastp_out = candidate_fa.with_name("cand_orf.blastp")
    db_prefix = Path("data") / "L1rpORF12p.fa"
    verify_blast_db(db_prefix)
    run_quiet(
        [
            "blastp",
            "-db",
            str(db_prefix),
            "-query",
            str(orf_fa),
            "-outfmt",
            "6 std qlen slen sacc",
            "-out",
            str(blastp_out),
        ],
        check=True,
    )
    _fix_blast_query_names(blastp_out)

    combined = candidate_fa.with_name("cand_orf_combine.blastp")
    find_longest_orf(blastp_out, combined)
    _fix_blast_query_names(combined)

    intact_file = candidate_fa.with_name("cand_orf_intact.blastp")
    find_intact_orf(combined, intact_file)
    _fix_blast_query_names(intact_file)

    with open(combined) as fh:
        for line in fh:
            if not line.strip():
                continue
            fields = line.strip().split()
            if len(fields) < 30:
                continue
            name = ",".join(fields[0].split(",")[:3])
            try:
                cov1 = int(fields[3]) / int(fields[13])
                cov2 = int(fields[18]) / int(fields[28])
            except (ValueError, ZeroDivisionError):
                continue
            if cov1 >= 0.9 and cov2 >= 0.9:
                present.add(name)

    with open(intact_file) as fh:
        for line in fh:
            if not line.strip():
                continue
            fields = line.strip().split()
            if len(fields) < 30:
                continue
            name = ",".join(fields[0].split(",")[:3])
            intact.add(name)

    return present, intact


def _validate_presence(candidate_fa: Path, min_length: int = 5000) -> Set[str]:
    """Return names of sequences aligning at least ``min_length`` bp to L1rp."""
    present: Set[str] = set()
    if candidate_fa.stat().st_size == 0:
        return present

    blastn_out = candidate_fa.with_suffix(".blastn")
    ref_fa = Path("data") / "L1rp.fa"
    run_quiet(
        [
            "blastn",
            "-query",
            str(candidate_fa),
            "-subject",
            str(ref_fa),
            "-outfmt",
            "6 std qlen slen",
            "-out",
            str(blastn_out),
        ],
        check=True,
    )

    longest: Dict[str, int] = {}
    with open(blastn_out) as fh:
        for line in fh:
            if not line.strip():
                continue
            f = line.strip().split()
            if len(f) < 14:
                continue
            name = ",".join(f[0].split(",")[:3])
            try:
                length = int(f[3])
            except ValueError:
                continue
            prev = longest.get(name, 0)
            if length > prev:
                longest[name] = length

    for name, aln_len in longest.items():
        if aln_len >= min_length:
            present.add(name)

    return present


def run_module2(
    input_fasta: str,
    sv_file: str,
    reference_fasta: str,
    output_dir: str,
    *,
    teref: str = "hprc",
    te: str = "L1,L1PA3",
    log: str | None = None,
    min_length: int = 5000,
    asm: int = 10,
) -> None:
    """RepeatMasker-free TE discovery using structural variants.

    ``log`` specifies a file to record malformed SV lines if provided.
    ``reference_fasta`` can be a local path or URL (downloaded if needed).
    ``te`` is a comma-separated list of TE families to search for.  Shortcuts
    follow :func:`haplongliner.extract_l1._expand_te_names` as in module 1.
    ``asm`` sets the minimap2 assembly preset (5, 10, or 20; default 10).
    """

    te_list = [t for t in te.split(",") if t]
    expanded_te = _expand_te_names(te_list)
    perform_orf = min_length >= 5000 and bool(expanded_te & {"L1HS", "L1PA2", "L1PA3"})

    print(
        "Module 2 running with:\n"
        f"  Input: {input_fasta}\n"
        f"  SV: {sv_file}\n"
        f"  Reference: {reference_fasta}\n"
        f"  Output Dir: {output_dir}\n"
        f"  TE types: {te} (min length {min_length})\n"
        f"  ASM preset: asm{asm}"
    )

    if not perform_orf:
        print(
            "[INFO] Skipping intact ORF detection and associated BLASTP steps "
            "(requires --length ≥5000 and --te including L1HS/L1PA2/L1PA3)"
        )

    print()

    outdir = Path(output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    verify_fasta_file(input_fasta)
    verify_sv_file(sv_file)

    print("[STEP 1] Preparing reference data")

    temp_files: List[Path] = []
    if teref == "hprc":
        raw_ref = Path("data") / "HPRC_L1_hs1_v2_v2fl.bed"
    elif teref in {"hs1", "hg38"}:
        urls = {
            "hs1": "https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.repeatMasker.out.gz",
            "hg38": "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.out.gz",
        }
        data_dir = Path("data")
        data_dir.mkdir(exist_ok=True)
        local_out = data_dir / Path(urls[teref]).name
        download_if_needed(urls[teref], local_out)
        raw_ref = _convert_rm_out_to_bed(local_out)
        temp_files.append(raw_ref)
    else:
        verify_repeatmasker_file(teref)
        if str(teref).endswith(('.out', '.out.gz')):
            raw_ref = _convert_rm_out_to_bed(Path(teref))
            temp_files.append(raw_ref)
        else:
            raw_ref = Path(teref)
    ref_bed = _filter_reference_bed(raw_ref, min_length, te, teref)
    temp_files.append(ref_bed)

    ref_path = reference_fasta
    if ref_path.startswith("http://") or ref_path.startswith("https://"):
        data_dir = Path("data")
        data_dir.mkdir(exist_ok=True)
        ref_local = data_dir / Path(ref_path).name
        ref_path = download_if_needed(ref_path, ref_local)

    verify_fasta_file(ref_path)

    print("\n[STEP 2] Mapping assemblies with minimap2")

    aln_paf = outdir / "genome_alignment.paf"
    with open(aln_paf, "w") as out:
        run_quiet(
            [
                "minimap2",
                "-x",
                f"asm{asm}",
                "-c",
                "--cs",
                str(input_fasta),
                str(ref_path),
            ],
            check=True,
            stdout=out,
        )

    print("\n[STEP 3] Lifting over candidate TE coordinates")

    script_path = Path(__file__).resolve().parents[1] / "scripts" / "liftover_paf.py"
    lifted_bed = outdir / "lifted.bed"
    with open(lifted_bed, "w") as out:
        run_quiet(
            [sys.executable, str(script_path), str(aln_paf), str(ref_bed)],
            check=True,
            stdout=out,
        )

    lifted_reorg = outdir / "lifted_reorg.bed"
    lifted = _create_lifted_reorg(lifted_bed, ref_bed, lifted_reorg)

    print("\n[STEP 4] Parsing structural variants")

    deletions, insertions = _parse_sv(Path(sv_file), Path(log) if log else None)

    print("\n[STEP 5] Validating candidate TEs")

    status, ins_seqs = _classify_sv(lifted, deletions, insertions, outdir, lifted_reorg)

    inter_ins = outdir / "intersect_ins.bed"
    extra_ins = _collect_long_insertions(insertions, inter_ins, min_length)

    candidate_fa = outdir / "cand.fa"
    _extract_sequences(
        Path(input_fasta),
        lifted,
        status,
        ins_seqs,
        candidate_fa,
        min_length,
        extra_ins,
    )

    if perform_orf:
        orf_present, intact_names = _validate_orfs(candidate_fa)
    else:
        print(
            "[INFO] Skipping intact ORF detection and BLASTP steps "
            "(requires --length ≥5000 and --te including L1HS/L1PA2/L1PA3)"
        )
        orf_present, intact_names = set(), set()
    if expanded_te & {"L1HS", "L1PA2", "L1PA3"}:
        presence_names = _validate_presence(candidate_fa, min_length)
    else:
        presence_names = set()
    presence_names.update(orf_present)

    sv_fa = outdir / "haplongliner_sv.fa"
    _write_sv_sequences(
        Path(input_fasta),
        lifted,
        status,
        ins_seqs,
        sv_fa,
        extra_ins,
        presence_names,
        intact_names,
    )

    print("\n[STEP 6] Writing output table")

    out_table = outdir / "haplongliner_sv.bed"
    with open(out_table, "w") as out:
        for (
            chrom,
            start,
            end,
            name,
            length,
            strand,
            plus_info,
            minus_info,
            t_start,
            t_end,
        ) in lifted:
            base_stat = status.get(name, "present")
            scaf, *_rest, t_strand = plus_info.split(",")
            target_len = t_end - t_start

            # Presence is determined solely by cand.blastn and
            # cand_orf_intact.blastp results. Any sequence found in
            # cand_orf_intact.blastp is labeled "intact"; those only in
            # cand.blastn are labeled "present". Everything else is
            # considered "absent".
            key = f"{name},{scaf},{t_start}"

            final_stat = "absent"
            if key in presence_names:
                final_stat = "present"
            if key in intact_names:
                final_stat = "intact"

            if name in ins_seqs:
                sv_stat = "INS"
            elif base_stat in {"missing", "absent"}:
                sv_stat = "DEL"
            else:
                sv_stat = "ALN"

            target_info = f"{scaf},{t_start},{t_end},{target_len},{t_strand},{sv_stat}"
            out.write(
                f"{chrom}\t{start}\t{end}\t{name}\t{length}\t{strand}\t{final_stat}\t{target_info}\n"
            )

        for chrom, start, end, seq, name in extra_ins:
            key = f"{name},{chrom},{start}"
            if key not in presence_names and key not in intact_names:
                continue

            final_stat = "present"
            if key in intact_names:
                final_stat = "intact"

            target_len = end - start
            target_info = f"{chrom},{start},{end},{target_len},.,INS"
            # mark non-reference insertions with a ';nr' suffix
            name_out = f"{name};nr"
            out.write(
                f"{chrom}\t{start}\t{end}\t{name_out}\t{target_len}\t.\t{final_stat}\t{target_info}\n"
            )

    print(f"Module 2 completed. Results in {out_table} and {sv_fa}")

    for tf in temp_files:
        try:
            os.remove(tf)
        except OSError:
            pass
