import os
import re
import sys
import gzip
import tempfile
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple, Iterable, Set, Optional
from collections import Counter

from .utils import (
    run_quiet,
    verify_fasta_file,
    verify_sv_file,
    verify_repeatmasker_file,
    verify_blast_db,
    read_nonempty_fasta,
    read_paf,
    _fix_blast_query_names,
    sort_bed,
    append_fasta,
    ensure_pyfaidx_fasta,
)
from .liftover_paf import liftover_paf
from .repeatmasker import read_collapsed_repeatmasker_out
from .resources import get_cache_dir, get_data_path
from pyfaidx import Fasta


def _revcomp(seq: str) -> str:
    complement = str.maketrans("ACGTacgtNn", "TGCAtgcaNn")
    return seq.translate(complement)[::-1]


def _parse_target_info(info: str) -> Tuple[str, int, int, str]:
    """Return ``(scaf, start, end, strand)`` from target info string."""
    parts = info.split(",")
    if len(parts) < 4:
        raise ValueError(f"Malformed info field: {info}")
    scaf = parts[0]
    start = int(parts[1])
    end = int(parts[2])
    if len(parts) >= 5:
        strand = parts[4]
    else:
        strand = parts[3]
    return scaf, start, end, strand


def _choose_lift_eval_interval(
    fa: Fasta,
    scaf: str,
    t_start: int,
    t_end: int,
    min_length: int,
) -> Tuple[int, int]:
    """Return target coordinates used to evaluate a lifted candidate.

    Short lifted spans can represent only an edge of the real target-genome
    element. For those loci, evaluate a wider rescue window while keeping the
    original lifted coordinates as the stable candidate identifier.
    """

    target_len = t_end - t_start
    if min_length <= 0 or target_len >= min_length:
        return t_start, t_end

    rescue_span = max(3 * min_length, target_len)
    center = (t_start + t_end) // 2
    eval_start = max(0, center - rescue_span // 2)
    eval_end = min(len(fa[scaf]), eval_start + rescue_span)
    if eval_end - eval_start < rescue_span:
        eval_start = max(0, eval_end - rescue_span)
    return eval_start, eval_end


from .rm_mode import download_if_needed, _fix_getorf_headers, parse_repeatmasker
from .extract_l1 import _expand_te_names


from .find_longest_orf import find_longest_orf
from .find_intact_orf import find_intact_orf
from .combine_table import _read_intact


# use shared PAF parser from utils for backward compatibility
_read_paf = read_paf


def _load_master_coords(paths: Iterable[Path]) -> Dict[str, Tuple[str, int, int, str]]:
    """Return mapping ``name -> (chrom, start, end, strand)`` from master BED files."""
    coords: Dict[str, Tuple[str, int, int, str]] = {}
    for path in paths:
        with open(path) as fh:
            for line in fh:
                if not line.strip() or line.startswith("#"):
                    continue
                fields = line.strip().split()
                if len(fields) < 5:
                    continue
                if len(fields) >= 6:
                    chrom, start, end, name, *_rest, strand = fields[:6]
                else:
                    chrom, start, end, name, strand = fields[:5]
                try:
                    coords[name] = (chrom, int(start), int(end), strand)
                except ValueError:
                    continue
    return coords


def _convert_rm_out_to_bed(out_path: Path) -> Path:
    """Convert RepeatMasker .out[.gz] file to temporary BED6 entries."""

    tmp = tempfile.NamedTemporaryFile("w", suffix=".bed", delete=False)
    with tmp:
        for hit in read_collapsed_repeatmasker_out(out_path):
            tmp.write(
                f"{hit.query_name}\t{hit.query_start}\t{hit.query_end}\t"
                f"{hit.family}\t{hit.length}\t{hit.strand}\n"
            )

    return Path(tmp.name)


def _liftover_l1s(
    aln_paf: Path,
    ref_bed: Path,
    min_length: int,
    master_files: Iterable[Path] | None = None,
    *,
    mapq: int = 0,
    min_align_len: int = 0,
    max_div: float = 2.0,
) -> List[Tuple[str, int, int, str, int, str, str, str, int, int]]:
    """Infer reference coordinates for each L1 using whole-genome alignments.

    ``aln_paf`` should be generated by mapping the target assembly to the
    reference assembly with minimap2 using the ``-c --cs`` options. ``ref_bed``
    must contain the L1 coordinates on the reference assembly. The returned list
    contains tuples of ``(chrom, start, end, name, length, strand, plus_info,
    minus_info, t_start, t_end)`` where ``plus_info`` and ``minus_info`` are
    ``scaffold,start,end,strand`` strings describing the lifted coordinates on
    the target assembly.

    ``mapq``, ``min_align_len`` and ``max_div`` are forwarded to ``liftover_paf``
    and default to ``-q 0 -l 0 -d 2.0``.
    """

    if master_files is None:
        master_files = [ref_bed]

    ref_coords = _load_master_coords(master_files)

    # run liftover_paf and capture the output
    import io
    import contextlib

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        # use permissive parameters so short alignments are retained
        # (-q 0 -l 0 -d 2.0 by default)
        liftover_paf(
            str(aln_paf),
            str(ref_bed),
            mapq,
            min_align_len,
            max_div,
            False,
        )

    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]] = []
    for line in buf.getvalue().splitlines():
        if not line.strip():
            continue
        fields = line.split("\t")
        if len(fields) < 6:
            continue
        t_chrom, t_start_s, t_end_s, name_field, _score, t_strand = fields[:6]
        try:
            t_start = int(t_start_s)
            t_end = int(t_end_s)
        except ValueError:
            continue
        try:
            _qchrom, q_start, q_end, _qstrand, q_name = name_field.split(",", 4)
        except ValueError:
            continue

        if q_name not in ref_coords:
            continue
        rchrom, rstart, rend, rstrand = ref_coords[q_name]
        length = rend - rstart
        if length < min_length:
            continue

        plus_info = f"{t_chrom},{t_start},{t_end},{t_strand}"
        minus_info = plus_info
        lifted.append(
            (
                rchrom,
                rstart,
                rend,
                q_name,
                length,
                rstrand,
                plus_info,
                minus_info,
                t_start,
                t_end,
            )
        )

    return lifted


def _write_bed(
    entries: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    path: Path,
) -> None:
    with open(path, "w") as out:
        for (
            chrom,
            start,
            end,
            name,
            length,
            strand,
            plus_info,
            minus_info,
            *_,
        ) in entries:
            out.write(
                f"{chrom}\t{start}\t{end}\t{name}\t{length}\t{strand}\t{plus_info}\t{minus_info}\n"
            )


def _read_lifted_bed(path: Path) -> Dict[str, List[Tuple[str, int, int, str, Set[str]]]]:
    """Return mapping ``id -> list of lifted coordinates`` from liftover_paf output."""

    lifted: Dict[str, List[Tuple[str, int, int, str, Set[str]]]] = {}
    with open(path) as fh:
        for line in fh:
            if not line.strip() or line.startswith("#"):
                continue
            fields = line.rstrip().split("\t")
            if len(fields) < 6:
                continue
            scaf, s_s, e_s, info, *_rest, strand = fields[:6]
            try:
                start = int(s_s)
                end = int(e_s)
            except ValueError:
                continue
            parts = info.split(",")
            if len(parts) < 5:
                continue
            qchrom, qs, qe, _qstrand, _name, *tags = parts
            key = f"{qchrom}:{qs}-{qe}"
            lifted.setdefault(key, []).append((scaf, start, end, strand, set(tags)))
    return lifted


def _filter_reference_bed(
    raw_ref: Path, min_length: int, te: str, teref: str
) -> Path:
    """Filter reference BED records by TE family and length.

    When ``teref`` is ``"hprc"`` the BED lacks TE family names in column 4.
    In that case assume all entries are L1 elements and only apply the
    length filter.
    """

    tmp = tempfile.NamedTemporaryFile("w", suffix=".bed", delete=False)
    if teref == "hprc":
        with open(raw_ref) as inp, open(tmp.name, "w") as out:
            for line in inp:
                if not line.strip() or line.startswith("#"):
                    continue
                fields = line.rstrip().split("\t")
                if len(fields) < 3:
                    continue
                try:
                    start = int(fields[1])
                    end = int(fields[2])
                except ValueError:
                    continue
                if (end - start) >= min_length:
                    out.write(line if line.endswith("\n") else line + "\n")
    else:
        run_quiet(
            [
                sys.executable,
                "-m",
                "haplongliner.extract_l1",
                str(raw_ref),
                "-o",
                tmp.name,
                "-l",
                str(min_length),
                "-t",
                te,
            ],
            check=True,
        )
    tmp.close()
    return Path(tmp.name)


def _create_lifted_reorg(
    lifted_bed: Path, ref_bed: Path, out_path: Path
) -> List[Tuple[str, int, int, str, int, str, str, str, int, int]]:
    """Write ``lifted_reorg.bed`` and return lifted entries for downstream steps."""

    mapping = _read_lifted_bed(lifted_bed)
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]] = []

    with open(ref_bed) as inp, open(out_path, "w") as out:
        for line in inp:
            if not line.strip() or line.startswith("#"):
                continue
            f = line.rstrip().split("\t")
            if len(f) < 6:
                continue
            chrom, start_s, end_s, _name, length_s, strand = f[:6]
            try:
                start = int(start_s)
                end = int(end_s)
                length = int(length_s)
            except ValueError:
                continue
            ref_status = f[6] if len(f) >= 7 else ("absent" if length <= 0 else "disrupted")

            key = f"{chrom}:{start}-{end}"
            infos = mapping.get(key)
            if not infos:
                out.write(
                    f"{chrom}\t{start}\t{end}\t{key}\t{length}\t{strand}\tna\t{ref_status}\n"
                )
                continue

            info_strs: List[str] = []
            for scaf, s, e, t_strand, tags in infos:
                tag_str = ""
                if "t5" in tags:
                    tag_str += ",t5"
                if "t3" in tags:
                    tag_str += ",t3"
                info = f"{scaf},{s},{e},{e - s},{t_strand}{tag_str}"
                info_strs.append(info)
                lifted.append(
                    (
                        chrom,
                        start,
                        end,
                        key,
                        length,
                        strand,
                        info,
                        info,
                        s,
                        e,
                    )
                )

            info_joined = ";".join(info_strs)
            out.write(
                f"{chrom}\t{start}\t{end}\t{key}\t{length}\t{strand}\t{info_joined}\t{ref_status}\n"
            )

    return lifted

def _parse_sv(
    sv_path: Path, log_path: Path | None = None
) -> Tuple[List[Tuple[str, int, int]], List[Tuple[str, int, int, str]]]:
    """Parse a simple VCF or BED SV file and return deletion and insertion regions.

    For insertions the inserted sequence is also returned if present. Unrecognized
    lines are written to ``log_path`` if provided."""
    deletions: List[Tuple[str, int, int]] = []
    insertions: List[Tuple[str, int, int, str]] = []
    is_vcf = sv_path.suffix.lower().endswith("vcf") or sv_path.suffix.lower() == ".gz"
    import gzip

    skipped: List[str] = []
    opener = gzip.open if str(sv_path).endswith(".gz") else open
    with opener(sv_path, "rt") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.rstrip().split("\t")
            if is_vcf or len(fields) > 5:
                try:
                    chrom = fields[0]
                    pos = int(fields[1]) - 1
                    info = fields[7] if len(fields) > 7 else ""
                    svtype = None
                    end = None
                    for item in info.split(";"):
                        if item.startswith("SVTYPE="):
                            svtype = item.split("=", 1)[1]
                        elif item.startswith("END="):
                            end = int(item.split("=", 1)[1]) - 1
                    if svtype == "DEL" and end is not None:
                        deletions.append((chrom, pos, end))
                    elif svtype == "INS":
                        alt = fields[4]
                        seq = "" if alt.startswith("<") else alt
                        insertions.append((chrom, pos, pos + 1, seq))
                except Exception:
                    skipped.append(line.rstrip())
            else:
                try:
                    chrom, start, end = fields[:3]
                    svtype = fields[3].upper() if len(fields) > 3 else ""
                    if svtype == "DEL":
                        deletions.append((chrom, int(start), int(end)))
                    elif svtype == "INS":
                        seq = fields[4] if len(fields) > 4 else ""
                        insertions.append((chrom, int(start), int(end), seq))
                except Exception:
                    skipped.append(line.rstrip())
    if log_path and skipped:
        with open(log_path, "w") as logf:
            logf.write("\n".join(skipped) + "\n")
    return deletions, insertions


def _bedtools_intersect(a: Path, b: Path, output: Path) -> None:
    with open(output, "w") as out:
        run_quiet(
            ["bedtools", "intersect", "-wa", "-wb", "-a", str(a), "-b", str(b)],
            check=True,
            stdout=out,
        )


def _collect_long_insertions(
    insertions: List[Tuple[str, int, int, str]],
    inter_ins: Path,
    min_length: int,
    max_length: int,
) -> List[Tuple[str, int, int, str, str]]:
    """Return insertion entries not overlapping lifted TEs within length bounds.

    The returned list contains tuples of ``(chrom, start, end, seq, name)`` where
    ``name`` is generated from the coordinates (``INS_<chrom>_<start>``).
    """

    overlapped: Set[Tuple[str, int, int]] = set()
    if inter_ins.exists():
        with open(inter_ins) as fh:
            for line in fh:
                f = line.strip().split("\t")
                if len(f) >= 11:
                    try:
                        chrom = f[7]
                        start = int(f[8])
                        end = int(f[9])
                    except ValueError:
                        continue
                    overlapped.add((chrom, start, end))

    extras: List[Tuple[str, int, int, str, str]] = []
    for chrom, start, end, seq in insertions:
        if (
            min_length <= len(seq) <= max_length
            and (chrom, start, end) not in overlapped
        ):
            name = f"INS_{chrom}_{start}"
            extras.append((chrom, start, end, seq, name))

    return extras


def _classify_sv(
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    deletions: List[Tuple[str, int, int]],
    insertions: List[Tuple[str, int, int, str]],
    outdir: Path,
    lifted_bed: Path,
) -> Tuple[Dict[str, str], Dict[str, str], Set[str]]:
    """Write SV BED files and intersect with lifted coordinates.

    Returns:
    - base status dictionary keyed by lifted TE name
    - insertion-sequence mapping keyed by lifted TE name
    - names overlapped by INS calls
    """

    del_bed = outdir / "sv_del.bed"
    ins_bed = outdir / "sv_ins.bed"

    with open(del_bed, "w") as out:
        for chrom, start, end in deletions:
            out.write(f"{chrom}\t{start}\t{end}\n")

    with open(ins_bed, "w") as out:
        for chrom, start, end, seq in insertions:
            out.write(f"{chrom}\t{start}\t{end}\t{seq}\n")

    inter_del = outdir / "intersect_del.bed"
    inter_ins = outdir / "intersect_ins.bed"
    _bedtools_intersect(lifted_bed, del_bed, inter_del)
    _bedtools_intersect(lifted_bed, ins_bed, inter_ins)

    del_names: Set[str] = set()
    if inter_del.exists():
        with open(inter_del) as fh:
            for line in fh:
                f = line.strip().split("\t")
                if len(f) >= 8:
                    del_names.add(f[3])

    ins_names: Set[str] = set()
    if inter_ins.exists():
        with open(inter_ins) as fh:
            for line in fh:
                f = line.strip().split("\t")
                if len(f) >= 11:
                    ins_names.add(f[3])

    status: Dict[str, str] = {}
    with open(lifted_bed) as fh:
        for line in fh:
            if not line.strip():
                continue
            parts = line.rstrip().split("\t")
            if len(parts) < 7:
                continue
            name = parts[3]
            ref_status = parts[7] if len(parts) >= 8 else ""
            if ref_status not in {"intact", "disrupted", "absent"}:
                try:
                    ref_len = int(parts[4])
                except ValueError:
                    ref_len = 0
                ref_status = "absent" if ref_len <= 0 else "disrupted"

            # Reference says absent: require an INS event to suggest presence.
            if ref_status == "absent":
                status[name] = "disrupted" if name in ins_names else "absent"
            # Reference says present (intact/disrupted): DEL suggests absence.
            else:
                status[name] = "absent" if name in del_names else "disrupted"

    ins_seqs: Dict[str, str] = {}

    with open(inter_ins) as fh:
        for line in fh:
            f = line.strip().split("\t")
            # expect 7 columns from lifted_reorg.bed and 4 from the insertion BED entry
            if len(f) >= 11:
                name = f[3]
                seq = f[10]
                ins_seqs[name] = seq

    return status, ins_seqs, ins_names


def _finalize_lifted_status(
    *,
    base_stat: str,
    intact_supported: bool,
    rm_supported: bool,
    is_insertion: bool,
    target_len: int,
    min_length: int,
) -> str:
    """Resolve the final status for a lifted candidate.

    For insertion-supported loci, RepeatMasker rescue still provides the
    disrupted fallback. For pure liftover (ALN) loci, a short unsupported lift
    should not default to ``disrupted`` merely because the locus lifted at all.
    """

    if intact_supported:
        return "intact"
    if is_insertion:
        if rm_supported:
            return "disrupted"
        return base_stat
    if base_stat == "absent":
        return "absent"
    if min_length > 0 and target_len < min_length:
        return "absent"
    return "disrupted"


def _intact_key_candidates(
    chrom: str, start: int, end: int, plus_info: str | None = None
) -> Set[str]:
    """Return possible presence/intact keys for a lifted candidate."""

    keys: Set[str] = {f"{chrom}_{start}_{end}"}
    if plus_info:
        parts = plus_info.split(",")
        if len(parts) >= 3:
            scaf = parts[0]
            scaf_start = parts[1]
            scaf_end = parts[2]

            # RepeatMasker presence detection stores target scaffold
            # coordinates as ``scaf_start_end``.  Include that key so the
            # RepeatMasker-derived presence set can match lifted candidates.
            keys.add(f"{scaf}_{scaf_start}_{scaf_end}")

            # SV-mode intact ORF keys from ``cand_orf_intact.blastp`` use
            # ``start-end_scaf_scaf_start_scaf_end`` (without reference chrom).
            # Include this form so intact calls propagate to final SV labels.
            keys.add(f"{start}-{end}_{scaf}_{scaf_start}_{scaf_end}")

            # Legacy intact detection also records entries using the
            # ``start-end,scaf,scaf_start`` convention; retain it for
            # compatibility with older outputs.
            span = f"{start}-{end}"
            keys.add(f"{span},{scaf},{scaf_start}")
    return keys


def _extract_sequences(
    fasta: Path,
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    out_lift: Path,
    out_ins: Path,
    insertions: List[Tuple[str, int, int, str]],
    min_length: int,
    max_length: int,
) -> Dict[str, Tuple[int, int]]:
    """Extract candidate TE and insertion sequences from the target assembly."""

    fa = Fasta(str(fasta))
    eval_intervals: Dict[str, Tuple[int, int]] = {}

    with open(out_lift, "w") as lift:
        for chrom, start, end, name, _, strand, plus_info, _, t_start, t_end in lifted:
            scaf, _ps, _pe, t_strand = _parse_target_info(plus_info)
            eval_start, eval_end = _choose_lift_eval_interval(
                fa, scaf, t_start, t_end, min_length
            )
            seq = fa[scaf][eval_start:eval_end].seq
            if t_strand == "-":
                seq = _revcomp(seq)
            seq = seq.upper()
            eval_intervals[name] = (eval_start, eval_end)
            header = (
                f"{chrom},{start},{end},{strand},{name},{scaf},{t_start},{t_end},{t_strand}"
            )
            lift.write(f">{header}\n{seq}\n")

    with open(out_ins, "w") as ins:
        for chrom, start, end, seq in insertions:
            if len(seq) < min_length or len(seq) > max_length:
                continue
            seq = seq.upper()
            name = f"INS_{chrom}_{start}"
            header = f"{chrom},{start},{end},+,{name}"
            ins.write(f">{header}\n{seq}\n")

    return eval_intervals


def _write_sv_sequences(
    fasta: Path,
    lifted: List[Tuple[str, int, int, str, int, str, str, str, int, int]],
    status: Dict[str, str],
    ins_seqs: Dict[str, str],
    out_fa: Path,
    min_length: int,
    max_length: int,
    extra_ins: List[Tuple[str, int, int, str, str]] | None = None,
    present: Set[str] | None = None,
    intact: Set[str] | None = None,
    eval_intervals: Dict[str, Tuple[int, int]] | None = None,
) -> None:
    """Write sequences from the target assembly for ALN and INS entries.

    Only insertion sequences with length between ``min_length`` and
    ``max_length`` are written to ``out_fa`` to avoid creating excessively
    large FASTA files for numerous short or very long insertions.
    """

    fa = Fasta(str(fasta))
    if present is None:
        present = set()
    if intact is None:
        intact = set()
    if eval_intervals is None:
        eval_intervals = {}
    extras = extra_ins or []

    with open(out_fa, "w") as out:
        for (
            _chrom,
            _start,
            _end,
            name,
            _length,
            _strand,
            plus_info,
            _minus_info,
            t_start,
            t_end,
        ) in lifted:
            base_stat = status.get(name, "disrupted")
            scaf, *_rest, t_strand = _parse_target_info(plus_info)
            seq_start, seq_end = t_start, t_end
            if base_stat == "intact":
                seq_start, seq_end = eval_intervals.get(name, (t_start, t_end))
            if base_stat == "absent":
                sv_stat = "DEL"
            elif name in ins_seqs:
                sv_stat = "INS"
            else:
                sv_stat = "ALN"

            target_info = (
                f"{scaf},{seq_start},{seq_end},{seq_end - seq_start},{t_strand},{sv_stat}"
            )

            if sv_stat == "ALN":
                seq = fa[scaf][seq_start:seq_end].seq
                if t_strand == "-":
                    seq = _revcomp(seq)
                out.write(f">{target_info}\n{seq}\n")
            elif sv_stat == "INS":
                seq = ins_seqs.get(name, "")
                if min_length <= len(seq) <= max_length:
                    out.write(f">{target_info}\n{seq}\n")

        for chrom, start, end, seq, name in extras:
            keys = _intact_key_candidates(chrom, start, end)
            if not any(k in present for k in keys) and not any(k in intact for k in keys):
                continue
            target_info = f"{chrom},{start},{end},{end - start},.,INS"
            out.write(f">{target_info}\n{seq}\n")


@dataclass(frozen=True)
class RepeatMaskerHit:
    """Summary of the dominant RepeatMasker annotation for a candidate."""

    family: str
    identity: float
    coverage: float


def _parse_repeatmasker(
    out_file: Path,
    seq_lengths: Dict[Tuple[str, str, str], int],
    cov_thresh: float,
) -> Tuple[Set[str], Dict[str, RepeatMaskerHit]]:
    """Return presence keys and annotation details derived from RepeatMasker output."""

    best_by_key: Dict[Tuple[str, str, str], Tuple[int, float, str]] = {}
    for hit in read_collapsed_repeatmasker_out(out_file):
        if not hit.is_l1:
            continue
        key_parts = hit.query_name.split(",")[:3]
        if len(key_parts) < 3:
            continue
        key = (key_parts[0], key_parts[1], key_parts[2])
        prev = best_by_key.get(key)
        score = (hit.covered_bp, hit.identity)
        if prev is None or score > prev[:2]:
            best_by_key[key] = (hit.covered_bp, hit.identity, hit.family)

    detailed: Dict[str, RepeatMaskerHit] = {}
    present: Set[str] = set()
    for key, (cov_bp, identity_pct, best_family) in best_by_key.items():
        key_len = seq_lengths.get(key, 0)
        if key_len <= 0:
            continue
        cov_frac = cov_bp / key_len
        cov_pct = cov_frac * 100.0
        if cov_pct > 100.0:
            cov_pct = 100.0
        if identity_pct > 100.0:
            identity_pct = 100.0
        name = "_".join(key)
        detailed[name] = RepeatMaskerHit(best_family, identity_pct, cov_pct)
        if cov_frac >= cov_thresh:
            present.add(name)

    return present, detailed


def _validate_orfs(candidate_fa: Path) -> Set[str]:
    """Detect intact ORFs in ``candidate_fa`` and return matching names."""

    intact: Set[str] = set()
    if candidate_fa.stat().st_size == 0:
        return intact

    # Generate ORFs in a file named ``cand_orf.fa`` to mirror RM mode
    print("[INFO] Using getorf -minsize 810 to retain ORFs ≥270 aa (≥80% of L1 ORF1)")
    orf_fa = candidate_fa.with_name("cand_orf.fa")
    run_quiet(
        [
            "getorf",
            "-sequence",
            str(candidate_fa),
            "-find",
            "1",
            "-outseq",
            str(orf_fa),
            "-minsize",
            "810",
        ],
        check=True,
    )
    _fix_getorf_headers(orf_fa, candidate_fa)
    filtered_fasta = read_nonempty_fasta(orf_fa)
    if not filtered_fasta:
        return intact

    blastp_out = candidate_fa.with_name("cand_orf.blastp")
    db_prefix = get_data_path("L1rpORF12p.fa")
    verify_blast_db(db_prefix)
    run_quiet(
        [
            "blastp",
            "-db",
            str(db_prefix),
            "-query",
            "-",
            "-outfmt",
            "6 std qlen slen sacc",
            "-out",
            str(blastp_out),
        ],
        input=filtered_fasta,
        text=True,
        check=True,
    )
    _fix_blast_query_names(blastp_out)

    combined = candidate_fa.with_name("cand_orf_combine.blastp")
    find_longest_orf(blastp_out, combined)
    _fix_blast_query_names(combined)

    intact_file = candidate_fa.with_name("cand_orf_intact.blastp")
    find_intact_orf(combined, intact_file)
    _fix_blast_query_names(intact_file)

    intact_records = _read_intact(intact_file)
    intact.update(intact_records.keys())
    return intact


def _append_liftover_orfs(orf_fa: Path, sv_fa: Path) -> None:
    """Append ORFs from liftover-derived sequences in ``sv_fa`` to ``orf_fa``.

    ``sv_fa`` contains sequences from the target assembly with headers formatted
    as ``chrom,start,end,length,strand,stat`` where ``stat`` is ``INS`` for
    insertion calls.  This function extracts ORFs from ``sv_fa`` using EMBOSS
    ``getorf`` and appends ORFs for records whose ``stat`` is not ``INS`` to the
    existing ``orf_fa`` file.
    """

    if not sv_fa.exists() or sv_fa.stat().st_size == 0:
        return

    mapping: Dict[str, str] = {}
    with open(sv_fa) as fh:
        for line in fh:
            if line.startswith(">"):
                name = line[1:].strip()
                mapping[name.replace(",", "_")] = name

    result = run_quiet(
        [
            "getorf",
            "-sequence",
            str(sv_fa),
            "-find",
            "1",
            "-outseq",
            "stdout",
            "-minsize",
            "810",
        ],
        check=True,
        text=True,
    )

    pattern = re.compile(r"^>([^\s]+)_([0-9]+)\s+\[([0-9]+)\s*-\s*([0-9]+)\]")
    records: List[str] = []
    write = False
    for line in result.stdout.splitlines():
        if line.startswith(">"):
            m = pattern.match(line)
            if m:
                name_key, idx, start, end = m.groups()
                orig = mapping.get(name_key, name_key)
                header = f">{orig},{idx},{start},{end}"
            else:
                header = line
            fields = header[1:].strip().split(",")
            write = len(fields) >= 6 and fields[5] != "INS"
            if write:
                records.append(header)
        else:
            if write:
                records.append(line)

    if not records:
        return

    with open(orf_fa, "ab+") as out:
        out.seek(0, os.SEEK_END)
        if out.tell() > 0:
            out.seek(-1, os.SEEK_END)
            if out.read(1) != b"\n":
                out.write(b"\n")
        for rec in records:
            out.write(rec.encode() + b"\n")


def _remove_empty_sequences(fasta_path: Path) -> None:
    """Remove records without sequence data from ``fasta_path`` in-place."""
    tmp_path = fasta_path.with_suffix(".tmp")
    with open(fasta_path) as src, open(tmp_path, "w") as dst:
        header = None
        seq_lines: List[str] = []

        def flush() -> None:
            if header and seq_lines:
                dst.write(header)
                if not header.endswith("\n"):
                    dst.write("\n")
                dst.writelines(seq_lines)

        for line in src:
            if line.startswith(">"):
                flush()
                header = line
                seq_lines = []
            else:
                if line.strip():
                    seq_lines.append(line)
        flush()

    tmp_path.replace(fasta_path)


def _shorten_fasta_headers(fasta_path: Path) -> tuple[Path, Path]:
    """Write a copy of ``fasta_path`` with short headers and record mapping.

    Returns the path to the short FASTA and the mapping list file.
    """
    short_fa = fasta_path.with_name(fasta_path.stem + "_short.fa")
    list_file = fasta_path.with_name("cand.list")
    with open(fasta_path) as src, open(short_fa, "w") as dst, open(list_file, "w") as lst:
        idx = 1
        for line in src:
            if line.startswith(">"):
                orig = line[1:].strip()
                name = f"seq{idx}"
                dst.write(f">{name}\n")
                lst.write(f"{name}\t{orig}\n")
                idx += 1
            else:
                dst.write(line)
    return short_fa, list_file


def _restore_rm_out_names(short_out: Path, list_file: Path, out_file: Path) -> None:
    """Restore original sequence names in RepeatMasker ``.out`` file."""
    mapping: Dict[str, str] = {}
    with open(list_file) as fh:
        for line in fh:
            if not line.strip():
                continue
            short, full = line.rstrip().split("\t", 1)
            mapping[short] = full

    with open(short_out) as src, open(out_file, "w") as dst:
        for line in src:
            parts = line.split()
            if (
                len(parts) > 4
                and parts[0].replace(".", "", 1).isdigit()
                and parts[4] in mapping
            ):
                parts[4] = mapping[parts[4]]
                line = " ".join(parts) + "\n"
            dst.write(line)


def _validate_presence(
    candidate_fa: Path, min_length: int = 5000, repeatmasker_pa: int = 4
) -> Tuple[Set[str], Dict[str, RepeatMaskerHit]]:
    """Annotate candidates with RepeatMasker and report presence keys."""

    present: Set[str] = set()
    annotations: Dict[str, RepeatMaskerHit] = {}
    _remove_empty_sequences(candidate_fa)
    if candidate_fa.stat().st_size == 0:
        return present, annotations

    seq_lengths: Dict[Tuple[str, str, str], int] = {}
    with open(candidate_fa) as fh:
        header: Optional[Tuple[str, str, str]] = None
        length = 0
        for line in fh:
            if line.startswith(">"):
                if header is not None:
                    seq_lengths[header] = length
                parts = line[1:].strip().split(",")
                if len(parts) >= 3:
                    header = (parts[0], parts[1], parts[2])
                else:
                    header = None
                length = 0
            else:
                length += len(line.strip())
        if header is not None:
            seq_lengths[header] = length
    short_fa, list_file = _shorten_fasta_headers(candidate_fa)

    try:
        run_quiet(
            [
                "RepeatMasker",
                "-e",
                "rmblast",
                "-pa",
                str(repeatmasker_pa),
                short_fa.name,
            ],
            cwd=candidate_fa.parent,
        )
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            "RepeatMasker failed while validating candidate sequences. "
            "Ensure RepeatMasker and the rmblast engine are installed and "
            "configured correctly."
        ) from exc

    short_out = candidate_fa.parent / (short_fa.name + ".out")
    rm_out = candidate_fa.with_suffix(candidate_fa.suffix + ".out")
    _restore_rm_out_names(short_out, list_file, rm_out)

    for ext in ["", ".out", ".masked", ".tbl", ".cat"]:
        tmp = short_fa.with_suffix(short_fa.suffix + ext)
        if tmp.exists():
            tmp.unlink()

    cov_thresh = 0.95
    present, annotations = _parse_repeatmasker(rm_out, seq_lengths, cov_thresh)

    return present, annotations


def run_sv_mode(
    input_fasta: str,
    sv_file: str,
    reference_fasta: str,
    output_dir: str,
    *,
    teref: str = "hprc",
    te: str = "L1,L1PA3",
    log: str | None = None,
    min_length: int = 0,
    asm: int = 10,
    xlength: int | None = None,
    exist: str = "no",
    repeatmasker_pa: int = 4,
) -> None:
    """RepeatMasker-free TE discovery using structural variants.

    ``log`` specifies a file to record malformed SV lines if provided.
    ``reference_fasta`` can be a local path or URL (downloaded if needed).
    ``te`` is a comma-separated list of TE families to search for.  Shortcuts
    follow :func:`haplongliner.extract_l1._expand_te_names` as in the RM mode.
    ``asm`` sets the minimap2 assembly preset (5, 10, or 20; default 10).
    ``exist`` determines whether to reuse an existing ``genome_alignment.paf``
    ("yes") or regenerate it ("no", default).
    """

    te_list = [t for t in te.split(",") if t]
    expanded_te = _expand_te_names(te_list)
    perform_orf = min_length >= 5000 and bool(expanded_te & {"L1HS", "L1PA2", "L1PA3"})
    if xlength is None:
        xlength = max(20000, 3 * min_length)

    info_lines = [
        "[INFO] SV mode running with:",
        f"[INFO]   Input: {input_fasta}",
        f"[INFO]   SV: {sv_file}",
        f"[INFO]   Reference: {reference_fasta}",
        f"[INFO]   Output Dir: {output_dir}",
        f"[INFO]   TE types: {te} (min length {min_length})",
        f"[INFO]   ASM preset: asm{asm}",
        f"[INFO]   Max insertion length: {xlength}",
        f"[INFO]   RepeatMasker -pa: {repeatmasker_pa}",
    ]
    print("\n".join(info_lines))

    if not perform_orf:
        print(
            "[INFO] Skipping intact ORF detection and associated BLASTP steps "
            "(requires --length ≥5000 and --te including L1HS/L1PA2/L1PA3)"
        )

    print()

    outdir = Path(output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    verify_fasta_file(input_fasta)
    input_fasta = str(ensure_pyfaidx_fasta(input_fasta))
    verify_sv_file(sv_file)

    print("[STEP 1] Preparing reference data")

    temp_files: List[Path] = []
    if teref == "hprc":
        raw_ref = get_data_path("HPRC_L1_hs1_v2_v2fl_status.bed")
    elif teref in {"hs1", "hg38"}:
        urls = {
            "hs1": "https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.repeatMasker.out.gz",
            "hg38": "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.out.gz",
        }
        local_out = get_cache_dir() / Path(urls[teref]).name
        download_if_needed(urls[teref], local_out)
        raw_ref = _convert_rm_out_to_bed(local_out)
        temp_files.append(raw_ref)
    else:
        verify_repeatmasker_file(teref)
        if str(teref).endswith(('.out', '.out.gz')):
            raw_ref = _convert_rm_out_to_bed(Path(teref))
            temp_files.append(raw_ref)
        else:
            raw_ref = Path(teref)
    if teref == "hprc":
        # The bundled HPRC reference is already restricted to L1 elements; retain
        # all entries as-is and skip the length/TE-family filtering step.
        ref_bed = raw_ref
    else:
        ref_bed = _filter_reference_bed(raw_ref, min_length, te, teref)
        temp_files.append(ref_bed)

    ref_path = reference_fasta
    if ref_path.startswith("http://") or ref_path.startswith("https://"):
        ref_local = get_cache_dir() / Path(ref_path).name
        ref_path = download_if_needed(ref_path, ref_local)

    verify_fasta_file(ref_path)
    ref_path = str(ensure_pyfaidx_fasta(ref_path))

    # Summary for Step 1
    ref_total = 0
    ref_te_counts: Counter[str] = Counter()
    with open(ref_bed) as fh:
        for line in fh:
            if not line.strip():
                continue
            ref_total += 1
            fields = line.strip().split()
            if len(fields) > 3:
                ref_te_counts[fields[3]] += 1
    te_type_count = len(ref_te_counts)
    msg = f"[SUM] Prepared reference with {ref_total} entries"
    if te_type_count:
        msg += f" across {te_type_count} TE types"
    print(msg)

    print("\n[STEP 2] Mapping assemblies with minimap2")

    aln_paf = outdir / "genome_alignment.paf"
    if exist == "yes" and aln_paf.exists():
        print("[INFO] Using existing genome_alignment.paf")
    else:
        with open(aln_paf, "w") as out:
            run_quiet(
                [
                    "minimap2",
                    "-x",
                    f"asm{asm}",
                    "-c",
                    "--cs",
                    str(input_fasta),
                    str(ref_path),
                ],
                check=True,
                stdout=out,
            )
    with open(aln_paf) as fh:
        alignments = sum(1 for _ in fh if _.strip())
    print(f"[SUM] Generated {alignments} alignment records")
    print("\n[STEP 3] Lifting over candidate TE coordinates")

    lifted_bed = outdir / "lifted.bed"
    print(
        "[INFO] Using "
        f"{alignments} alignment records (MAPQ ≥0, min length ≥0, max divergence ≤2.0) "
        f"from {aln_paf} with reference intervals {ref_bed} -> {lifted_bed}"
    )
    import contextlib

    with open(lifted_bed, "w") as out, contextlib.redirect_stdout(out):
        liftover_paf(str(aln_paf), str(ref_bed), 0, 0, 2.0, False, show_progress=False)

    with open(lifted_bed) as lifted_fh:
        raw_lifted_records = sum(1 for line in lifted_fh if line.strip())
    print(
        f"[INFO] Liftover produced {raw_lifted_records} raw intervals written to {lifted_bed}"
    )

    lifted_reorg = outdir / "lifted_reorg.bed"
    lifted = _create_lifted_reorg(lifted_bed, ref_bed, lifted_reorg)
    print(f"[SUM] Lifted {len(lifted)} TE candidates")

    print("\n[STEP 4] Parsing structural variants")

    deletions, insertions = _parse_sv(Path(sv_file), Path(log) if log else None)
    print(f"[SUM] Parsed {len(deletions)} deletions and {len(insertions)} insertions")

    print("\n[STEP 5] Validating candidate TEs")

    status, ins_seqs, ins_names = _classify_sv(
        lifted, deletions, insertions, outdir, lifted_reorg
    )

    inter_ins = outdir / "intersect_ins.bed"
    extra_ins = _collect_long_insertions(insertions, inter_ins, min_length, xlength)

    candidate_lift_fa = outdir / "cand_lift.fa"
    candidate_ins_fa = outdir / "cand_ins.fa"
    print(f"[INFO] Ignoring insertion sequences >{xlength} bp for cand_ins.fa")
    eval_intervals = _extract_sequences(
        Path(input_fasta),
        lifted,
        candidate_lift_fa,
        candidate_ins_fa,
        insertions,
        min_length,
        xlength,
    )
    candidate_fa = outdir / "cand.fa"
    candidate_fa.write_text("")
    append_fasta(candidate_fa, candidate_lift_fa)
    append_fasta(candidate_fa, candidate_ins_fa)

    if perform_orf:
        print(
            "[INFO] Using getorf -minsize 810 to retain ORFs ≥270 aa (≥80% of L1 ORF1)"
        )
        orf_fa = candidate_fa.with_name("cand_orf.fa")
        run_quiet(
            [
                "getorf",
                "-sequence",
                str(candidate_fa),
                "-find",
                "1",
                "-outseq",
                str(orf_fa),
                "-minsize",
                "810",
            ],
            check=True,
        )
        _fix_getorf_headers(orf_fa, candidate_fa)
        blastp_out = candidate_fa.with_name("cand_orf.blastp")
        db_prefix = get_data_path("L1rpORF12p.fa")
        verify_blast_db(db_prefix)
        filtered_fasta = read_nonempty_fasta(orf_fa)
        if filtered_fasta:
            run_quiet(
                [
                    "blastp",
                    "-db",
                    str(db_prefix),
                    "-query",
                    "-",
                    "-outfmt",
                    "6 std qlen slen sacc",
                    "-out",
                    str(blastp_out),
                ],
                input=filtered_fasta,
                text=True,
                check=True,
            )
            _fix_blast_query_names(blastp_out)
        else:
            blastp_out.touch()
        combined = candidate_fa.with_name("cand_orf_combine.blastp")
        find_longest_orf(blastp_out, combined)
        _fix_blast_query_names(combined)
        intact_file = candidate_fa.with_name("cand_orf_intact.blastp")
        find_intact_orf(combined, intact_file)
        _fix_blast_query_names(intact_file)
        intact_records = _read_intact(intact_file)
        intact_names = set(intact_records.keys())
    else:
        print(
            "[INFO] Skipping intact ORF detection and BLASTP steps "
            "(requires --length ≥5000 and --te including L1HS/L1PA2/L1PA3)"
        )
        intact_names = set()
        candidate_fa.with_name("cand_orf_intact.blastp").touch()
    if expanded_te & {"L1HS", "L1PA2", "L1PA3"}:
        presence_names, rm_annotations = _validate_presence(
            candidate_fa,
            min_length,
            repeatmasker_pa=repeatmasker_pa,
        )
    else:
        presence_names = set()
        rm_annotations = {}

    # Summary for Step 5
    status_counts = Counter(status.values())
    num_statuses = len(status_counts)
    print(
        f"[SUM] Classified {len(status)} lifted TEs across {num_statuses} status categories; "
        f"intact: {len(intact_names)}; extra insertions: {len(extra_ins)}"
    )

    print("\n[STEP 6] Writing output files")

    out_table = outdir / "haplongliner_sv.bed"
    final_status: Dict[str, str] = {}
    with open(out_table, "w") as out:
        for (
            chrom,
            start,
            end,
            name,
            length,
            strand,
            plus_info,
            minus_info,
            t_start,
            t_end,
        ) in lifted:
            base_stat = status.get(name, "disrupted")
            scaf, _ps, _pe, t_strand = _parse_target_info(plus_info)
            target_len = t_end - t_start

            keys = _intact_key_candidates(chrom, start, end, plus_info)
            rm_supported = any(k in presence_names for k in keys)
            intact_supported = any(k in intact_names for k in keys)
            is_insertion = name in ins_names or name in ins_seqs

            final_stat = _finalize_lifted_status(
                base_stat=base_stat,
                intact_supported=intact_supported,
                rm_supported=rm_supported,
                is_insertion=is_insertion,
                target_len=target_len,
                min_length=min_length,
            )
            final_status[name] = final_stat

            out_t_start, out_t_end = t_start, t_end
            if final_stat == "intact" and not is_insertion:
                out_t_start, out_t_end = eval_intervals.get(name, (t_start, t_end))

            annotation_label = None
            for key in keys:
                hit = rm_annotations.get(key)
                if hit:
                    annotation_label = f"{hit.family}({hit.identity:.1f},{hit.coverage:.1f})"
                    break
            te_label = annotation_label or name

            if final_stat == "absent":
                sv_stat = "DEL"
            elif is_insertion:
                sv_stat = "INS"
            else:
                sv_stat = "ALN"

            target_info = (
                f"{scaf},{out_t_start},{out_t_end},{out_t_end - out_t_start},{t_strand},{sv_stat}"
            )
            out.write(
                f"{chrom}\t{start}\t{end}\t{te_label}\t{length}\t{strand}\t{final_stat}\t{target_info}\n"
            )

        for chrom, start, end, seq, name in extra_ins:
            keys = _intact_key_candidates(chrom, start, end)
            if not any(k in presence_names for k in keys) and not any(
                k in intact_names for k in keys
            ):
                continue

            final_stat = "disrupted"
            if any(k in intact_names for k in keys):
                final_stat = "intact"

            target_len = end - start
            target_info = f"{chrom},{start},{end},{target_len},.,INS"
            # mark non-reference insertions with a ';nr' suffix
            name_out = f"{name};nr"
            annotation_label = None
            for key in keys:
                hit = rm_annotations.get(key)
                if hit:
                    annotation_label = f"{hit.family}({hit.identity:.1f},{hit.coverage:.1f})"
                    break
            te_label = annotation_label or name_out
            out.write(
                f"{chrom}\t{start}\t{end}\t{te_label}\t{target_len}\t.\t{final_stat}\t{target_info}\n"
            )

    sort_bed(out_table)

    sv_fa = outdir / "haplongliner_sv.fa"
    _write_sv_sequences(
        Path(input_fasta),
        lifted,
        final_status,
        ins_seqs,
        sv_fa,
        min_length,
        xlength,
        extra_ins,
        presence_names,
        intact_names,
        eval_intervals,
    )

    if perform_orf:
        _append_liftover_orfs(candidate_fa.with_name("cand_orf.fa"), sv_fa)

    # Summary for Step 6
    total_final = 0
    final_status_counts: Counter[str] = Counter()
    final_te_counts: Counter[str] = Counter()
    with open(out_table) as fh:
        for line in fh:
            if not line.strip():
                continue
            total_final += 1
            fields = line.strip().split()
            if len(fields) > 3:
                final_te_counts[fields[3]] += 1
            if len(fields) > 6:
                final_status_counts[fields[6]] += 1
    status_count = len(final_status_counts)
    te_type_count = len(final_te_counts)
    print(
        f"[SUM] Final table has {total_final} entries across {status_count} status categories and {te_type_count} TE types"
    )

    print(f"[INFO] SV mode completed. Results in {out_table} and {sv_fa}")

    for tf in temp_files:
        try:
            os.remove(tf)
        except OSError:
            pass
